apiVersion: v1
kind: Pod
metadata:
  name: fastapi-ml
  labels:
    app: fastapi-ml
spec:
  containers:
    - image: marinazav/online_inference:v2
      imagePullPolicy: "Always"
      name: fastapi-ml
      ports:
        - containerPort: 8000
      resources:
        requests:
          memory: "64Mi"
          cpu: "500m"
        limits:
          memory: "512Mi"
          cpu: "1000m"
      readinessProbe:
        httpGet:
          path: /healthz
          port: 8000
        initialDelaySeconds: 5
        periodSeconds: 3
      livenessProbe:
        httpGet:
          path: /healthz
          port: 8000
        initialDelaySeconds: 45
        periodSeconds: 3