apiVersion: v1
kind: Pod
metadata:
  name: fastapi-ml
  labels:
    app: fastapi-ml
spec:
  containers:
    - image: marinazav/online_inference:v1
      name: fastapi-ml
      ports:
        - containerPort: 8000
      resources:
        requests:
          memory: "64Mi"
          cpu: "500m"
        limits:
          memory: "512Mi"
          cpu: "1000m"